export const SEED_USERS = [
  {
    id: 'u-demo',
    email: 'demo@firma.cz',
    password: 'demo123',
    role: 'user',
    plan: 'PRO',
    obor: 'IT a technologie',
    kraj: 'Jihomoravský',
    velikost_firmy: 'do 10 zaměstnanců',
    onboarding_complete: true,
    notification_prefs: {
      frequency: 'okamzite',
      poskytovatele: { EU: true, MPO: true, MMR: true, Kraj: true, SFŽP: true, MZe: true, MPSV: true, ČMZRB: true },
    },
    created_at: '2026-05-12',
  },
  {
    id: 'u-admin',
    email: 'admin@hlidacdotaci.cz',
    password: 'admin123',
    role: 'admin',
    plan: 'FIRMA',
    obor: null,
    kraj: null,
    velikost_firmy: null,
    onboarding_complete: true,
    notification_prefs: { frequency: 'okamzite', poskytovatele: {} },
    created_at: '2026-01-01',
  },
  {
    id: 'u-jana',
    email: 'jana.novakova@firma.cz',
    password: 'heslo123',
    role: 'user',
    plan: 'FREE',
    obor: 'Cestovní ruch a pohostinství',
    kraj: 'Jihočeský',
    velikost_firmy: 'OSVČ',
    onboarding_complete: true,
    notification_prefs: {
      frequency: 'tydenni',
      poskytovatele: { EU: true, MPO: true, MMR: true, Kraj: true, SFŽP: false, MZe: false, MPSV: false, ČMZRB: false },
    },
    created_at: '2026-06-01',
  },
  {
    id: 'u-petr',
    email: 'petr.svoboda@stavby.cz',
    password: 'heslo123',
    role: 'user',
    plan: 'FIRMA',
    obor: 'Stavebnictví',
    kraj: 'Hlavní město Praha',
    velikost_firmy: 'do 50 zaměstnanců',
    onboarding_complete: true,
    notification_prefs: {
      frequency: 'okamzite',
      poskytovatele: { EU: true, MPO: true, MMR: true, Kraj: true, SFŽP: true, MZe: true, MPSV: true, ČMZRB: true },
    },
    created_at: '2026-03-20',
  },
];

export const SEED_CALLS = [
  {
    id: 'c1',
    nazev: 'OP TAK – Digitální podnik',
    poskytovatel: 'EU',
    obory: ['IT a technologie', 'Obchod a služby', 'Výroba a průmysl'],
    kraje: ['Celá ČR'],
    velikosti: ['OSVČ', 'do 10 zaměstnanců', 'do 50 zaměstnanců'],
    min_castka: 100000,
    max_castka: 3000000,
    deadline: '2026-09-30',
    popis: 'Podpora zavádění pokročilých digitálních technologií (ERP, CRM, cloud, kybernetická bezpečnost) do provozu malých a středních podniků. Určeno firmám, které chtějí digitalizovat interní procesy nebo výrobu.',
    url: 'https://optak.cz/digitalni-podnik',
    stav: 'aktivni',
    created_at: '2026-06-28',
  },
  {
    id: 'c2',
    nazev: 'OP TAK – Úspory energie',
    poskytovatel: 'EU',
    obory: ['Výroba a průmysl', 'Zemědělství'],
    kraje: ['Celá ČR'],
    velikosti: ['do 10 zaměstnanců', 'do 50 zaměstnanců', '50+ zaměstnanců'],
    min_castka: 500000,
    max_castka: 15000000,
    deadline: '2026-07-18',
    popis: 'Dotace na snížení energetické náročnosti výrobních provozů – zateplení budov, rekuperace tepla, výměna technologií za úspornější varianty.',
    url: 'https://optak.cz/uspory-energie',
    stav: 'aktivni',
    created_at: '2026-05-10',
  },
  {
    id: 'c3',
    nazev: 'OP Zaměstnanost+ – Rekvalifikace zaměstnanců',
    poskytovatel: 'EU',
    obory: ['Obchod a služby', 'Výroba a průmysl', 'Doprava a logistika', 'Ostatní'],
    kraje: ['Celá ČR'],
    velikosti: ['do 10 zaměstnanců', 'do 50 zaměstnanců', '50+ zaměstnanců'],
    min_castka: 50000,
    max_castka: 2000000,
    deadline: '2026-10-31',
    popis: 'Podpora rekvalifikace a dalšího vzdělávání zaměstnanců v souvislosti se změnami na trhu práce a zaváděním nových technologií.',
    url: 'https://esfcr.cz/rekvalifikace',
    stav: 'aktivni',
    created_at: '2026-04-01',
  },
  {
    id: 'c4',
    nazev: 'OP JAK – Podpora vzdělávání zaměstnanců',
    poskytovatel: 'EU',
    obory: ['Vzdělávání', 'Zdravotnictví a sociální služby', 'Ostatní'],
    kraje: ['Celá ČR'],
    velikosti: ['OSVČ', 'do 10 zaměstnanců', 'do 50 zaměstnanců'],
    min_castka: 30000,
    max_castka: 800000,
    deadline: '2026-08-01',
    popis: 'Finanční podpora vzdělávacích a školicích institucí a firem poskytujících odborné vzdělávání a rekvalifikační kurzy.',
    url: 'https://opjak.cz/vzdelavani',
    stav: 'aktivni',
    created_at: '2026-03-15',
  },
  {
    id: 'c5',
    nazev: 'SFŽP – Nová zelená úsporám pro podnikatele',
    poskytovatel: 'SFŽP',
    obory: ['Energetika a životní prostředí', 'Výroba a průmysl', 'Zemědělství'],
    kraje: ['Celá ČR'],
    velikosti: ['OSVČ', 'do 10 zaměstnanců', 'do 50 zaměstnanců', '50+ zaměstnanců'],
    min_castka: 100000,
    max_castka: 5000000,
    deadline: '2026-12-15',
    popis: 'Podpora instalace obnovitelných zdrojů energie, fotovoltaických elektráren a úsporných opatření v podnikatelských objektech.',
    url: 'https://sfzp.cz/nzu-podnikatele',
    stav: 'aktivni',
    created_at: '2026-06-30',
  },
  {
    id: 'c6',
    nazev: 'Jihomoravský inovační voucher',
    poskytovatel: 'Kraj',
    obory: ['IT a technologie', 'Výroba a průmysl', 'Kreativní průmysly'],
    kraje: ['Jihomoravský'],
    velikosti: ['OSVČ', 'do 10 zaměstnanců', 'do 50 zaměstnanců'],
    min_castka: 20000,
    max_castka: 300000,
    deadline: '2026-07-12',
    popis: 'Podpora spolupráce malých a středních podniků s výzkumnými organizacemi na inovativních projektech v Jihomoravském kraji.',
    url: 'https://jic.cz/inovacni-voucher',
    stav: 'aktivni',
    created_at: '2026-05-20',
  },
  {
    id: 'c7',
    nazev: 'Podpora cestovního ruchu – Jihočeský kraj',
    poskytovatel: 'Kraj',
    obory: ['Cestovní ruch a pohostinství', 'Obchod a služby'],
    kraje: ['Jihočeský'],
    velikosti: ['OSVČ', 'do 10 zaměstnanců', 'do 50 zaměstnanců'],
    min_castka: 50000,
    max_castka: 500000,
    deadline: '2026-09-01',
    popis: 'Dotace na rozvoj turistické infrastruktury, ubytovacích kapacit a doprovodných služeb cestovního ruchu v Jihočeském kraji.',
    url: 'https://kraj-jihocesky.cz/cestovni-ruch',
    stav: 'aktivni',
    created_at: '2026-06-15',
  },
  {
    id: 'c8',
    nazev: 'MPO – Marketing pro malé a střední podniky',
    poskytovatel: 'MPO',
    obory: ['Obchod a služby', 'Kreativní průmysly', 'Cestovní ruch a pohostinství'],
    kraje: ['Celá ČR'],
    velikosti: ['OSVČ', 'do 10 zaměstnanců', 'do 50 zaměstnanců'],
    min_castka: 30000,
    max_castka: 400000,
    deadline: '2026-07-16',
    popis: 'Podpora účasti malých a středních podniků na zahraničních veletrzích a tvorby marketingových materiálů pro export.',
    url: 'https://mpo.cz/marketing-msp',
    stav: 'aktivni',
    created_at: '2026-06-01',
  },
  {
    id: 'c9',
    nazev: 'PGRLF – Podpora zemědělských podnikatelů',
    poskytovatel: 'MZe',
    obory: ['Zemědělství'],
    kraje: ['Celá ČR'],
    velikosti: ['OSVČ', 'do 10 zaměstnanců', 'do 50 zaměstnanců', '50+ zaměstnanců'],
    min_castka: 100000,
    max_castka: 4000000,
    deadline: '2026-11-30',
    popis: 'Zvýhodněné úvěry a podpory pro zemědělské podnikatele na investice do modernizace strojů a zemědělských staveb.',
    url: 'https://pgrlf.cz/podpora',
    stav: 'aktivni',
    created_at: '2026-02-10',
  },
  {
    id: 'c10',
    nazev: 'ČMZRB – Záruka Expanze',
    poskytovatel: 'ČMZRB',
    obory: ['Výroba a průmysl', 'Obchod a služby', 'Doprava a logistika', 'IT a technologie'],
    kraje: ['Celá ČR'],
    velikosti: ['do 10 zaměstnanců', 'do 50 zaměstnanců'],
    min_castka: 500000,
    max_castka: 20000000,
    deadline: '2026-12-31',
    popis: 'Zvýhodněné záruky k úvěrům na investiční projekty malých a středních podniků realizované mimo Prahu.',
    url: 'https://cmzrb.cz/zaruka-expanze',
    stav: 'aktivni',
    created_at: '2026-01-15',
  },
  {
    id: 'c11',
    nazev: 'MMR – Podpora obnovy venkova',
    poskytovatel: 'MMR',
    obory: ['Stavebnictví', 'Zemědělství', 'Ostatní'],
    kraje: ['Celá ČR'],
    velikosti: ['OSVČ', 'do 10 zaměstnanců'],
    min_castka: 50000,
    max_castka: 1000000,
    deadline: '2026-08-31',
    popis: 'Podpora obnovy a rozvoje venkovské infrastruktury a drobného podnikání v obcích do 3000 obyvatel.',
    url: 'https://mmr.cz/obnova-venkova',
    stav: 'aktivni',
    created_at: '2026-06-29',
  },
  {
    id: 'c12',
    nazev: 'OP TAK – Inovace produktová a procesní',
    poskytovatel: 'EU',
    obory: ['Výroba a průmysl', 'IT a technologie'],
    kraje: ['Celá ČR'],
    velikosti: ['do 10 zaměstnanců', 'do 50 zaměstnanců', '50+ zaměstnanců'],
    min_castka: 1000000,
    max_castka: 25000000,
    deadline: '2026-10-15',
    popis: 'Podpora zavádění inovovaných nebo zcela nových produktů a výrobních procesů s vyšší přidanou hodnotou.',
    url: 'https://optak.cz/inovace',
    stav: 'aktivni',
    created_at: '2026-05-01',
  },
  {
    id: 'c13',
    nazev: 'Praha – Voucher na inovace',
    poskytovatel: 'Kraj',
    obory: ['IT a technologie', 'Kreativní průmysly', 'Zdravotnictví a sociální služby'],
    kraje: ['Hlavní město Praha'],
    velikosti: ['OSVČ', 'do 10 zaměstnanců', 'do 50 zaměstnanců'],
    min_castka: 50000,
    max_castka: 1000000,
    deadline: '2026-07-25',
    popis: 'Podpora pražských firem při vývoji nových produktů a služeb ve spolupráci s vysokými školami a výzkumnými centry.',
    url: 'https://praha.eu/voucher-inovace',
    stav: 'aktivni',
    created_at: '2026-06-27',
  },
  {
    id: 'c14',
    nazev: 'OP TAK – Robotizace a automatizace výroby',
    poskytovatel: 'EU',
    obory: ['Výroba a průmysl'],
    kraje: ['Celá ČR'],
    velikosti: ['do 10 zaměstnanců', 'do 50 zaměstnanců', '50+ zaměstnanců'],
    min_castka: 500000,
    max_castka: 10000000,
    deadline: '2026-09-10',
    popis: 'Podpora nasazení robotických a automatizačních technologií do výrobních linek za účelem zvýšení produktivity.',
    url: 'https://optak.cz/robotizace',
    stav: 'aktivni',
    created_at: '2026-04-20',
  },
  {
    id: 'c15',
    nazev: 'MPSV – Podpora zaměstnávání OZP',
    poskytovatel: 'MPSV',
    obory: ['Obchod a služby', 'Výroba a průmysl', 'Zdravotnictví a sociální služby', 'Ostatní'],
    kraje: ['Celá ČR'],
    velikosti: ['OSVČ', 'do 10 zaměstnanců', 'do 50 zaměstnanců', '50+ zaměstnanců'],
    min_castka: 20000,
    max_castka: 500000,
    deadline: '2026-07-14',
    popis: 'Příspěvek zaměstnavatelům na vytvoření a provoz pracovních míst pro osoby se zdravotním postižením.',
    url: 'https://mpsv.cz/podpora-ozp',
    stav: 'aktivni',
    created_at: '2026-06-05',
  },
];
